### ISSUE TITLE
remove leading "-" from filenames

### ISSUE THREAD

**Issue by rur0** [davidmz/go-charset#1]
When I try to 
```bash
$ go get -u github.com/davidmz/go-charset
```
I get
``` bash
$ go get -u github.com/davidmz/go-charset
package github.com/davidmz/go-charset: invalid input file name "-ascii.go"
```

I suppose it is the leading character "-" that is causing the issue

**Comment by davidmz** [comment]
Yes, you are right. This package was created 7 years ago, and the current Go version doesn't handle these filenames. Honestly, I don't remember, why I choose this naming:)

By the way, I don't recommend to use this package because the official _charmap_ package (https://godoc.org/golang.org/x/text/encoding/charmap) do the same. 

I will freeze this repository and recommend to use _charmap_ instead.
